name: Generate docs

on:
  push:
    branches:
      - "main"
      - "docs"
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: "ubuntu-latest"
    name: "Generate docs"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs
          fetch-depth: 0 # fetch all commits/branches
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        name: "Cache Python dependencies (mkdocs-material and mike)"
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Add git user for mike
        run: |
          git config --global user.name GitHub Actions
          git config --global user.email actions@github.com
      - name: "Deploy documentation"
        run: mike deploy v0.9.0 latest -u --push

  # deploy-api-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         persist-credentials: false
  #     - uses: crystal-lang/install-crystal@v1
  #       with:
  #         crystal: latest
  #     - name: "Install shards"
  #       run: shards install
  #     - name: "Generate docs"
  #       run: crystal docs
  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./docs/api
